RUN apt-get install -y wget && wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz && tar -xf Python-3.8.2.tgz

RUN /bin/bash -c "./Python-3.8.2/configure --enable-optimizations" && make -j 1 && make altinstall